python main.py --num-stream-jobs 1000 --num-stream-jobs-factor 1.05\
                --num-curriculum-time 1 \
                --algo lacie_ppo_memory \
                --clip-param 0.1\
                --ppo-epoch 4\
                --num-env-steps 50000000\
                --gamma 1\
                --entropy-coef 0.01\
                --regularize-coef 1\
                --load-balance-service-rates 0.15 0.25 0.35 0.45 0.55 0.65 0.75 0.85 0.95 1.05 \
                --reward-norm-factor 10000\
                --lr 0.0001\
                --cpc-lr 0.001\
                --num-mini-batch 4\
                --adapt-lr 1e-3\
                --num-inner-steps 5\
                --lacie-batch-size 32\
                --lacie-buffer-size 400\
                --lacie-num-iter 40\
                --num-process 16 --num-steps 1000 --log-interval 5 \
                --seed 100 --use-memory-to-pred-weights --use-linear-lr-decay\
                --log-dir lacie_ppo_2