from .least_work import LeastWorkAgent
from .shortest_processing_time import ShortestProcessingTimeAgent
from .random_allocate import RandomAllocateAgent
from .earliest_completion_time import EarliestCompletionTimeAgent
